### ISSUE TITLE
Setting pod labels does not trigger operations

### ISSUE THREAD

**Issue by jsanda** [Orange-OpenSource/cassandra-k8s-operator#66]
I followed the instructions in the [operations guide](https://github.com/Orange-OpenSource/cassandra-k8s-operator/blob/master/documentation/operations.md#operationcleanup) to run `cleanup` on my nodes, but nothing happens.

Here is my cluster manifest:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: jolokia-auth
type: Opaque
data:
  password: TTBucDQ1NXcwcmQ=
  username: am9sb2tpYS11c2Vy
---
apiVersion: "db.orange.com/v1alpha1"
kind: "CassandraCluster"
metadata:
  name: cassandra-demo
  labels:
    cluster: k8s.kaas
spec:
  baseImage: orangeopensource/cassandra-image
  version: 3.11.4-8u212-0.3.1-cqlsh
  dataCapacity: "20Gi"
  imagepullpolicy: IfNotPresent
  imageJolokiaSecret:
    name: jolokia-auth
  hardAntiAffinity: false       
  deletePVC: true
  autoPilot: false
  gcStdout: false
  autoUpdateSeedList: false
  maxPodUnavailable: 1
  runAsUser: 1000
  resources:
    requests:
      cpu: '500m'
      memory: 1Gi
    limits:
      cpu: '500m'
      memory: 1Gi
  topology:
    dc:
      - name: dc1
        nodesPerRacks: 2
        rack:
          - name: rack1
```

I set the pod labels with:

```
$ kubectl label -l cassandracluster=cassandra-demo pod operation-name=cleanup operation-status=ToDo --overwrite
```

Here is my cluster status which never changes:

```yaml
  status:
    cassandraRackStatus:
      dc1-rack1:
        cassandraLastAction:
          Name: Initializing
          endTime: "2019-07-19T00:20:29Z"
          status: Done
        phase: Running
        podLastOperation: {}
    lastClusterAction: Initializing
    lastClusterActionStatus: Done
    phase: Running
    seedlist:
    - cassandra-demo-dc1-rack1-0.cassandra-demo-dc1.default
    - cassandra-demo-dc1-rack1-1.cassandra-demo-dc1.default
```
The behavior is the same regardless of the operation I specify.

Am I doing something incorrectly?
